import = [
 "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[font]
normal.family = "CaskaydiaCove Nerd Font"

size = 14.0
  
[window]
opacity = 0.8
#blur = true

[env]
TERM = "xterm-256color"









