
[font]
normal.family = "CaskaydiaCove Nerd Font"

size = 13.5
  
[window]
opacity = 0.9
#blur = true

[env]
TERM = "xterm-256color"

[general]
import = [
 "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]









